export const FETCH_GOODS_INFO = Symbol('FETCH_GOODS_INFO');
export const FETCH_GOODS_INFO_SUCCESS = Symbol('FETCH_GOODS_INFO_SUCCESS');
export const FETCH_GOODS_INFO_FAIL = Symbol('FETCH_GOODS_INFO_FAIL');