export const FETCH_MEDICINE_CODE = Symbol('FETCH_MEDICINE_CODE');
export const FETCH_MEDICINE_CODE_SUCCESS = Symbol('FETCH_MEDICINE_CODE_SUCCESS');
export const FETCH_MEDICINE_CODE_FAIL = Symbol('FETCH_MEDICINE_CODE_FAIL');