export const GET_MEDICINE_CODE = Symbol('GET_MEDICINE_CODE');
export const GET_MEDICINE_CODE_SUCCESS = Symbol('GET_MEDICINE_CODE_SUCCESS');
export const GET_MEDICINE_CODE_FAIL = Symbol('GET_MEDICINE_CODE_FAIL');