// 获取账户列表
export const FETCH_ACCOUNT_LIST = Symbol('FETCH_ACCOUNT_LIST');
export const FETCH_ACCOUNT_LIST_SUCCESS = Symbol('FETCH_ACCOUNT_LIST_SUCCESS');
export const FETCH_ACCOUNT_LIST_FAIL = Symbol('FETCH_ACCOUNT_LIST_FAIL');

// 获取账户信息
export const FETCH_ACCOUNT = Symbol('FETCH_ACCOUNT');
export const FETCH_ACCOUNT_SUCCESS = Symbol('FETCH_ACCOUNT_SUCCESS');
export const FETCH_ACCOUNT_FAIL = Symbol('FETCH_ACCOUNT_FAIL');