export const FETCH_SECOND = Symbol('FETCH_SECOND');
export const FETCH_SECOND_SUCCESS = Symbol('FETCH_SECOND_SUCCESS');
export const FETCH_SECOND_FAIL = Symbol('FETCH_SECOND_FAIL');

export const GET_MEDICINE_CODE = Symbol('GET_MEDICINE_CODE');
export const GET_MEDICINE_CODE_SUCCESS = Symbol('GET_MEDICINE_CODE_SUCCESS');
export const GET_MEDICINE_CODE_FAIL = Symbol('GET_MEDICINE_CODE_FAIL');